## <font color='green'>***Generation of Fake University Data For Analysis***</font>

### <font color='green'>***Session 1 : Library Support***</font>

In [1]:
import random 
import pandas as pd        
import names 
import mysql.connector
from tqdm import tqdm,trange

### <font color='green'>***Session 2 : Variable Assignment & Loop Automation***

<font color='green'>***i) Variable Assignment***</font>

In [2]:
courses=[
    'Computer Science','Applied Statistics','Information Science',
    'Business Management','Acturial Science','Education',
    'Criminalogy','Engineering','BioChemistry','Pharmaceutical Science','Clinical Medicine']
sex=['male','female']
years=[1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005]
adm=[]
months=[1,2,3,4,5,6,7,8,9,10,11,12]
days=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
campuses=['SpongeBob SquarePants University','Patrick Star University','Sandy Cheeks University','Squidward Tentacles University','Old Man Jenkins University','Larry The Lobster University']
reside=['Campus Hostel','Rental Room']
reasons=['Privacy','Finance','Security','Health Risk','Infrastructure','Peer Pressure']
domain=['@gmail.com','@yahoo.com']
ph=[num for num in range(999)]
id_num=[num for num in range(1000,10000)]
rating_c=[1,2,3,4,5]
rating_r=[1,2,3,4,5]
rating_u=[1,2,3,4,5]

<font color='green'>***ii) Loop Automation***</font>

In [3]:
std_id=[]
full_names=[]
birth_date=[]
adm=[]
genders=[]
major=[]
email=[]
campus=[]
resident=[]
reason=[]
rating_course=[]
rating_university=[]
rating_residence=[]

for index in trange(500000):
    sexes=random.choice(sex)
    majors=random.choice(courses)
    fname=names.get_full_name(gender=sexes)
    if sexes == 'male':
        full_names.append(fname)
        genders.append('Male')
        day=str(random.choice(days))
        month=str(random.choice(months))
        year=str(random.choice(years))
        if month == 2 and day > 28:
            day=str(28)
        elif month == 4 and day > 31:
            day=str(30)
        elif month == 6 and day > 31:
            day=str(30)
        elif month == 9 and day > 31:
            day=str(30)
        elif month == 11 and day > 31:
            day=str(30)
        dates='/'.join([year,month,day])
        birth_date.append(dates)
        adm_year=str(int(year) + 18)
        adm_month=str(random.choice(months))
        adm_day=str(random.choice(days))
        if adm_month == 2 and adm_day > 28:
            adm_day=str(28)
        elif adm_month == 4 and adm_day > 31:
            adm_day=str(30)
        elif adm_month == 6 and adm_day > 31:
            adm_day=str(30)
        elif adm_month == 9 and adm_day > 31:
            adm_day=str(30)
        elif adm_month == 11 and adm_day > 31:
            adm_day=str(30)
        adm.append('/'.join([adm_year,adm_month,adm_day]))
        if majors == 'Computer Science':
            major.append(majors)
            nums=f"COM/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Applied Statistics':
            major.append(majors)
            nums=f"AST/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Information Science':
            major.append(majors)
            nums=f"IFS/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Business Management':
            major.append(majors)
            nums=f"BSM/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Acturial Science':
            major.append(majors)
            nums=f"ACS/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Education':
            major.append(majors)
            nums=f"EDU/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Criminalogy':
            major.append(majors)
            nums=f"CRI/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Engineering':
            major.append(majors)
            nums=f"ENG/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'BioChemistry':
            major.append(majors)
            nums=f"BIO/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Pharmaceutical Science':
            major.append(majors)
            nums=f"PHR/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Clinical Medicine':
            major.append(majors)
            nums=f"CLM/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        campus.append(random.choice(campuses))
        resident.append(random.choice(reside))
        reason.append(random.choice(reasons))
        rating_course.append(random.choice(rating_c))
        rating_residence.append(random.choice(rating_r))
        rating_university.append(random.choice(rating_u))
        f=fname.lower().split()
        emails=f"{''.join(f)}{random.choice(ph)}{random.choice(domain)}"
        email.append(emails)
    else:
        full_names.append(fname)
        genders.append('Female')
        day=str(random.choice(days))
        month=str(random.choice(months))
        year=str(random.choice(years))
        if month == 2 and day > 28:
            day=str(28)
        elif month == 4 and day > 31:
            day=str(30)
        elif month == 6 and day > 31:
            day=str(30)
        elif month == 9 and day > 31:
            day=str(30)
        elif month == 11 and day > 31:
            day=str(30)
        dates='/'.join([year,month,day])
        birth_date.append(dates)
        adm_year=str(int(year) + 18)
        adm_month=str(random.choice(months))
        adm_day=str(random.choice(days))
        if adm_month == 2 and adm_day > 28:
            adm_day=str(28)
        elif adm_month == 4 and adm_day > 31:
            adm_day=str(30)
        elif adm_month == 6 and adm_day > 31:
            adm_day=str(30)
        elif adm_month == 9 and adm_day > 31:
            adm_day=str(30)
        elif adm_month == 11 and adm_day > 31:
            adm_day=str(30)
        adm.append('/'.join([adm_year,adm_month,adm_day]))
        if majors == 'Computer Science':
            major.append(majors)
            nums=f"COM/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Applied Statistics':
            major.append(majors)
            nums=f"AST/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Information Science':
            major.append(majors)
            nums=f"IFS/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Business Management':
            major.append(majors)
            nums=f"BSM/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Acturial Science':
            major.append(majors)
            nums=f"ACS/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Education':
            major.append(majors)
            nums=f"EDU/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Criminalogy':
            major.append(majors)
            nums=f"CRI/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Engineering':
            major.append(majors)
            nums=f"ENG/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'BioChemistry':
            major.append(majors)
            nums=f"BIO/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Pharmaceutical Science':
            major.append(majors)
            nums=f"PHR/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        elif majors == 'Clinical Medicine':
            major.append(majors)
            nums=f"CLM/{random.choice(id_num)}/{adm_year[-2:]}"
            std_id.append(nums)
        campus.append(random.choice(campuses))
        resident.append(random.choice(reside))
        reason.append(random.choice(reasons))
        rating_course.append(random.choice(rating_c))
        rating_residence.append(random.choice(rating_r))
        rating_university.append(random.choice(rating_u))
        f=fname.lower().split()
        emails=f"{''.join(f)}{random.choice(ph)}{random.choice(domain)}"
        email.append(emails)

100%|██████████| 500000/500000 [1:26:09<00:00, 96.72it/s]

### <font color='green'>***Session 3 : Load Generated Data into DataFrame***

In [4]:
data=pd.DataFrame({
    'Student ID':std_id,
    'Full Name':full_names,
    'Gender':genders,
    'Birth_Date':birth_date,
    'Course Name':major,
    'Course Rating':rating_course,
    'University Name':campus,
    'University Rating':rating_university,
    'Admission_Date':adm,
    'Residence':resident,
    'Reason':reason,
    'Residence Rating':rating_residence,
    'Email':email
})

In [5]:
data

,Student ID,Full Name,Gender,Birth_Date,Course Name,Course Rating,University Name,University Rating,Admission_Date,Residence,Reason,Residence Rating,Email
0,BSM/7450/16,Jimmie Cash,Female,1998/9/26,Business Management,1,Patrick Star University,5,2016/12/11,Rental Room,Security,4,jimmiecash715@yahoo.com
1,ENG/2664/19,Wendell Pulse,Male,2001/4/22,Engineering,2,Old Man Jenkins University,4,2019/9/20,Campus Hostel,Peer Pressure,5,wendellpulse914@gmail.com
2,ACS/2271/16,Sharyn Beier,Female,1998/10/2,Acturial Science,5,Patrick Star University,4,2016/4/13,Campus Hostel,Privacy,3,sharynbeier4@yahoo.com
3,EDU/7172/18,Susan Greiner,Female,2000/2/21,Education,5,SpongeBob SquarePants University,1,2018/8/13,Rental Room,Finance,1,susangreiner175@gmail.com
4,CRI/3238/21,Joyce Frazier,Female,2003/2/15,Criminalogy,2,SpongeBob SquarePants University,5,2021/5/16,Campus Hostel,Infrastructure,3,joycefrazier250@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,AST/6294/19,Kimberly Connor,Female,2001/3/10,Applied Statistics,1,SpongeBob SquarePants University,4,2019/4/10,Campus Hostel,Peer Pressure,3,kimberlyconnor172@yahoo.com
499996,ACS/5391/16,Phyllis Basham,Female,1998/2/17,Acturial Science,3,Squidward Tentacles University,1,2016/9/5,Campus Hostel,Security,4,phyllisbasham550@gmail.com
499997,IFS/2920/18,Lloyd Gonzalez,Male,2000/11/1,Information Science,3,Squidward Tentacles University,4,2018/8/9,Campus Hostel,Security,3,lloydgonzalez562@yahoo.com
499998,CRI/6016/21,Kayla Williams,Female,2003/1/14,Criminalogy,5,SpongeBob SquarePants University,4,2021/10/30,Campus Hostel,Peer Pressure,3,kaylawilliams870@yahoo.com
499999,EDU/6272/23,Erwin Morton,Male,2005/12/16,Education,5,SpongeBob SquarePants University,2,2023/12/15,Campus Hostel,Security,5,erwinmorton408@gmail.com

In [6]:
print(f'Duplicates for Entire Dataset : {data.duplicated().sum()}')
print(f"Duplicates for Student ID : {data['Student ID'].duplicated().sum()}")
print(f"Duplicates for Full Name : {data['Full Name'].duplicated().sum()}")

Duplicates for Entire Dataset : 0
Duplicates for Student ID : 99154
Duplicates for Full Name : 90006

### <font color='green'>***Session 4 : Save Output***

In [7]:
data.to_csv('fake_campus_data.csv',index=False)

In [17]:
data.rename(columns={
    'University Name':'University_Name'
},inplace=True)

In [21]:
sponge=data.query('University_Name == "SpongeBob SquarePants University"')
patrick=data.query('University_Name == "Patrick Star University"')
sandy=data.query('University_Name == "Sandy Cheeks University"')
jenkins=data.query('University_Name == "Old Man Jenkins University"')
laary=data.query('University_Name == "Larry The Lobster University"')
squidward=data.query('University_Name == "Squidward Tentacles University"')

In [29]:
from sqlalchemy import create_engine

In [40]:
engine=create_engine('mariadb://root:pandas@localhost:3307/Larry The Lobster University')

In [41]:
laary.to_sql('student_data',engine,index=False)

83571